### PR TITLE
adds ability to select theme and fixes ghpages 404 error

### PR DESCRIPTION
**Pull request by trevormast**
Addresses issues:
#49
#50
#55

### CODE REVIEW

**Comment by trevormast** [comment]
Links direct to user's root url (ie. user.github.io) instead of given path.

**Comment by trevormast** [comment]
Fixed link references with latest commit: d00ddda

**Comment by amoose** [comment]
Woop woop! This is awesome! There are a few tweaks for fine tuning, but this works great!

**Comment by amoose** [comment]
- [x] site's root url is adding extra slash
  - http://amoose.github.io/qw//posts/2013/12/09/example-post.html
  - http://amoose.github.io/qq/about/

**Pull request merged**
